value_for_label_encoder = 8
baseline_knn_neighbour = 5
baseline_knn_metrics = 'minkowski'
baseline_knn_p =2
baseline_dt_criterion = "entropy"
baseline_rf_criterion = "entropy"
baseline_rf_n_estimators = 100
set_limit_for_knn = 25
baseline_lr_solver = 'liblinear'
baseline_lr_class_weight = 'balanced'
